---
  - name: Ensure Apache is installed
    yum:
      name: httpd
      state: present
  - name: Ensure Apache service is running
    systemd:
      name: httpd
      state: started
      enabled: yes
    become: yes
    tags: httpd
